scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add randoblight dummy
scoreboard objectives add createwaygate dummy
scoreboard objectives add waygatemake dummy
scoreboard objectives add regatetime dummy
scoreboard objectives add machin_shin_clk dummy
scoreboard objectives add ms_done dummy
scoreboard objectives add ms_effect_clock dummy
scoreboard objectives add pigmenmad dummy
scoreboard objectives add DT dummy
scoreboard objectives add AT dummy
scoreboard objectives add reguz dummy
scoreboard objectives add GT dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add hwait dummy
scoreboard objectives add stamina dummy
scoreboard objectives add streg dummy
scoreboard objectives add streg1 dummy
scoreboard objectives add stamina dummy
scoreboard objectives add insomnia dummy
scoreboard objectives add regud dummy
scoreboard objectives add blocktd dummy
scoreboard objectives add dsreg dummy
scoreboard objectives add treg dummy
scoreboard objectives add thirst dummy
scoreboard objectives add insomnia dummy
scoreboard objectives add thirst dummy
scoreboard objectives add slimeTick dummy
scoreboard objectives add slimeSize dummy
scoreboard objectives add slimeNegate dummy
scoreboard objectives add slimeTick dummy
scoreboard objectives add slimeSize dummy
scoreboard objectives add slimeNegate dummy
scoreboard objectives add MMEffectTick dummy
scoreboard objectives add regulatef dummy
scoreboard objectives add regulateg dummy
scoreboard objectives add healthb dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add td dummy
scoreboard objectives add regulate dummy
scoreboard objectives add entd dummy
scoreboard objectives add ent dummy
scoreboard objectives add entad dummy
scoreboard objectives add enta dummy
scoreboard objectives add entskeleton dummy
scoreboard objectives add entspider dummy
scoreboard objectives add entcreeper dummy
scoreboard objectives add entpig dummy
scoreboard objectives add entcow dummy
scoreboard objectives add entsheep dummy
scoreboard objectives add entchicken dummy
scoreboard objectives add entsawayig dummy
scoreboard objectives add vregu dummy
scoreboard objectives add regu dummy
scoreboard objectives add regun dummy
scoreboard objectives add atic dummy
scoreboard objectives add lreg dummy
scoreboard objectives add blocktc dummy
scoreboard objectives add path dummy
scoreboard objectives add loadclock dummy
scoreboard objectives add debug dummy
scoreboard objectives add vreg dummy
scoreboard objectives add vwlt dummy
scoreboard objectives add storm_clk dummy
scoreboard objectives add wt_done dummy
scoreboard objectives add wt_effect_clock dummy
scoreboard objectives add wt_tick dummy
scoreboard objectives add wtdummytic dummy
scoreboard objectives add windpulse dummy
scoreboard objectives add listindex dummy
scoreboard objectives add randoblight dummy
scoreboard objectives add createwaygate dummy
scoreboard objectives add waygatemake dummy
scoreboard objectives add regatetime dummy
scoreboard objectives add machin_shin_clk dummy
scoreboard objectives add ms_done dummy
scoreboard objectives add ms_effect_clock dummy
scoreboard objectives add pigmenmad dummy
scoreboard objectives add DT dummy
scoreboard objectives add AT dummy
scoreboard objectives add reguz dummy
scoreboard objectives add GT dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add hwait dummy
scoreboard objectives add stamina dummy
scoreboard objectives add streg dummy
scoreboard objectives add streg1 dummy
scoreboard objectives add stamina dummy
scoreboard objectives add insomnia dummy
scoreboard objectives add regud dummy
scoreboard objectives add blocktd dummy
scoreboard objectives add dsreg dummy
scoreboard objectives add treg dummy
scoreboard objectives add thirst dummy
scoreboard objectives add insomnia dummy
scoreboard objectives add thirst dummy
scoreboard objectives add slimeTick dummy
scoreboard objectives add slimeSize dummy
scoreboard objectives add slimeNegate dummy
scoreboard objectives add slimeTick dummy
scoreboard objectives add slimeSize dummy
scoreboard objectives add slimeNegate dummy
scoreboard objectives add MMEffectTick dummy
scoreboard objectives add regulatef dummy
scoreboard objectives add regulateg dummy
scoreboard objectives add healthb dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add td dummy
scoreboard objectives add regulate dummy
scoreboard objectives add vregu dummy
scoreboard objectives add regu dummy
scoreboard objectives add regun dummy
scoreboard objectives add atic dummy
scoreboard objectives add lreg dummy
scoreboard objectives add blocktc dummy
scoreboard objectives add path dummy
scoreboard objectives add loadclock dummy
scoreboard objectives add debug dummy
scoreboard objectives add vreg dummy
scoreboard objectives add vwlt dummy
scoreboard objectives add storm_clk dummy
scoreboard objectives add wt_done dummy
scoreboard objectives add wt_effect_clock dummy
scoreboard objectives add wt_tick dummy
scoreboard objectives add wtdummytic dummy
scoreboard objectives add windpulse dummy
scoreboard objectives add listindex dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.const dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.const dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add randoblight dummy
scoreboard objectives add rblight dummy
scoreboard objectives add createwaygate dummy
scoreboard objectives add waygatedone dummy
scoreboard objectives add gateopen dummy
scoreboard objectives add regate dummy
scoreboard objectives add regatetime dummy
scoreboard objectives add regate dummy
scoreboard objectives add regatetime dummy
scoreboard objectives add ms_distance dummy
scoreboard objectives add ms_distance_int dummy
scoreboard objectives add machin_shin_inta dummy
scoreboard objectives add machin_shin_intb dummy
scoreboard objectives add machin_shin_clk dummy
scoreboard objectives add ms_effect_clock dummy
scoreboard objectives add pigmenmad dummy
scoreboard objectives add DB dummy
scoreboard objectives add DT dummy
scoreboard objectives add DB dummy
scoreboard objectives add AT dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add EF dummy
scoreboard objectives add reguz dummy
scoreboard objectives add GT dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add hwait dummy
scoreboard objectives add DB dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add streg dummy
scoreboard objectives add streg1 dummy
scoreboard objectives add stamina dummy
scoreboard objectives add climb dummy
scoreboard objectives add crouch dummy
scoreboard objectives add jump dummy
scoreboard objectives add dealt dummy
scoreboard objectives add sprint dummy
scoreboard objectives add sneaktime dummy
scoreboard objectives add swim dummy
scoreboard objectives add walkowater dummy
scoreboard objectives add walk dummy
scoreboard objectives add walkuwater dummy
scoreboard objectives add insomniaderp dummy
scoreboard objectives add ADD dummy
scoreboard objectives add regud dummy
scoreboard objectives add dsreg dummy
scoreboard objectives add vwl dummy
scoreboard objectives add vwlt dummy
scoreboard objectives add vwl dummy
scoreboard objectives add thirst dummy
scoreboard objectives add treg dummy
scoreboard objectives add drink dummy
scoreboard objectives add thirst dummy
scoreboard objectives add insomnia dummy
scoreboard objectives add DB dummy
scoreboard objectives add DT dummy
scoreboard objectives add death dummy
scoreboard objectives add DB dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add thirst dummy
scoreboard objectives add slimeTick dummy
scoreboard objectives add slimeNegate dummy
scoreboard objectives add slimeTick dummy
scoreboard objectives add slimeNegate dummy
scoreboard objectives add MMfix dummy
scoreboard objectives add MyddraalHit dummy
scoreboard objectives add MyddraalHitb dummy
scoreboard objectives add MMEffectTick dummy
scoreboard objectives add healthb dummy
scoreboard objectives add regulatef dummy
scoreboard objectives add regulateg dummy
scoreboard objectives add outindex dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add ar_ef_cl_max dummy
scoreboard objectives add all_max dummy
scoreboard objectives add arrow_max dummy
scoreboard objectives add cave_spider_max dummy
scoreboard objectives add cod_max dummy
scoreboard objectives add drag_fire_max dummy
scoreboard objectives add enderman_max dummy
scoreboard objectives add endermite_max dummy
scoreboard objectives add evoker_max dummy
scoreboard objectives add evoker_fangs_max dummy
scoreboard objectives add exper_orb_max dummy
scoreboard objectives add eye_of_end_max dummy
scoreboard objectives add falling_bl_max dummy
scoreboard objectives add hoglin_max dummy
scoreboard objectives add illusioner_max dummy
scoreboard objectives add item_max dummy
scoreboard objectives add fireball_max dummy
scoreboard objectives add llama_spit_max dummy
scoreboard objectives add magma_cube_max dummy
scoreboard objectives add phantom_max dummy
scoreboard objectives add pig_max dummy
scoreboard objectives add piglin_max dummy
scoreboard objectives add piglin_brute_max dummy
scoreboard objectives add pufferfish_max dummy
scoreboard objectives add salmon_max dummy
scoreboard objectives add shulker_max dummy
scoreboard objectives add shu_bul_max dummy
scoreboard objectives add silverfish_max dummy
scoreboard objectives add skeleton_max dummy
scoreboard objectives add slime_max dummy
scoreboard objectives add smal_fire_max dummy
scoreboard objectives add snowball_max dummy
scoreboard objectives add spec_ar_max dummy
scoreboard objectives add spider_max dummy
scoreboard objectives add stray_max dummy
scoreboard objectives add egg_max dummy
scoreboard objectives add ender_pearl_max dummy
scoreboard objectives add exper_bot_max dummy
scoreboard objectives add potion_max dummy
scoreboard objectives add vex_max dummy
scoreboard objectives add vindicator_max dummy
scoreboard objectives add witch_max dummy
scoreboard objectives add with_skul_max dummy
scoreboard objectives add zoglin_max dummy
scoreboard objectives add zombie_max dummy
scoreboard objectives add zom_pig_max dummy
scoreboard objectives add fish_bob_max dummy
scoreboard objectives add sawayig_max dummy
scoreboard objectives add blight_max dummy
scoreboard objectives add machin_shin_max dummy
scoreboard objectives add startworldclock dummy
scoreboard objectives add listindex dummy
scoreboard objectives add loadclock dummy
scoreboard objectives add td dummy
scoreboard objectives add regulate dummy
scoreboard objectives add entd dummy
scoreboard objectives add ent dummy
scoreboard objectives add entad dummy
scoreboard objectives add enta dummy
scoreboard objectives add entskeleton dummy
scoreboard objectives add entspider dummy
scoreboard objectives add entcreeper dummy
scoreboard objectives add entpig dummy
scoreboard objectives add entcow dummy
scoreboard objectives add entsheep dummy
scoreboard objectives add entchicken dummy
scoreboard objectives add entsawayig dummy
scoreboard objectives add vregu dummy
scoreboard objectives add regu dummy
scoreboard objectives add regun dummy
scoreboard objectives add atic dummy
scoreboard objectives add blockt2 dummy
scoreboard objectives add lreg dummy
scoreboard objectives add blocktc dummy
scoreboard objectives add moriatica dummy
scoreboard objectives add moriatic dummy
scoreboard objectives add wmoriatic dummy
scoreboard objectives add systic dummy
scoreboard objectives add extrastic dummy
scoreboard objectives add path dummy
scoreboard objectives add blockta dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vpol1 dummy
scoreboard objectives add vpol2 dummy
scoreboard objectives add vpol3 dummy
scoreboard objectives add vpol4 dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vpol1 dummy
scoreboard objectives add vpol2 dummy
scoreboard objectives add vpol3 dummy
scoreboard objectives add vpol4 dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vreg dummy
scoreboard objectives add vwl dummy
scoreboard objectives add vwlt dummy
scoreboard objectives add vwl dummy
scoreboard objectives add vtc dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vpol1 dummy
scoreboard objectives add vpol2 dummy
scoreboard objectives add vpol3 dummy
scoreboard objectives add vpol4 dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vpol1 dummy
scoreboard objectives add vpol2 dummy
scoreboard objectives add vpol3 dummy
scoreboard objectives add vpol4 dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vwl dummy
scoreboard objectives add vwlt dummy
scoreboard objectives add vwl dummy
scoreboard objectives add vtc dummy
scoreboard objectives add aboveground dummy
scoreboard objectives add wt_distancea dummy
scoreboard objectives add wt_distance_inta dummy
scoreboard objectives add wt dummy
scoreboard objectives add storm_inta dummy
scoreboard objectives add storm_intb dummy
scoreboard objectives add storm_clk dummy
scoreboard objectives add wt_distancea dummy
scoreboard objectives add wt_distanceb dummy
scoreboard objectives add wt_distancec dummy
scoreboard objectives add wt dummy
scoreboard objectives add wt_effect_clock dummy
scoreboard objectives add wt_tick dummy
scoreboard objectives add weather dummy
scoreboard objectives add wn_derpa dummy
scoreboard objectives add wn_derpb dummy
scoreboard objectives add windpulse dummy
scoreboard objectives add wind dummy
scoreboard objectives add windspeed dummy
scoreboard objectives add listindex dummy
scoreboard objectives add startworldclock dummy
scoreboard objectives add randoblight dummy
scoreboard objectives add rblight dummy
scoreboard objectives add createwaygate dummy
scoreboard objectives add waygatedone dummy
scoreboard objectives add gateopen dummy
scoreboard objectives add regate dummy
scoreboard objectives add regatetime dummy
scoreboard objectives add regate dummy
scoreboard objectives add regatetime dummy
scoreboard objectives add ms_distance dummy
scoreboard objectives add ms_distance_int dummy
scoreboard objectives add machin_shin_inta dummy
scoreboard objectives add machin_shin_intb dummy
scoreboard objectives add machin_shin_clk dummy
scoreboard objectives add ms_effect_clock dummy
scoreboard objectives add pigmenmad dummy
scoreboard objectives add DB dummy
scoreboard objectives add DT dummy
scoreboard objectives add DB dummy
scoreboard objectives add AT dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add EF dummy
scoreboard objectives add reguz dummy
scoreboard objectives add GT dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add slow_minact_tier dummy
scoreboard objectives add slow_boolean dummy
scoreboard objectives add slow_max_tier dummy
scoreboard objectives add minf_minact_tier dummy
scoreboard objectives add minf_boolean dummy
scoreboard objectives add minf_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add blin_minact_tier dummy
scoreboard objectives add blin_boolean dummy
scoreboard objectives add blin_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add poi_minact_tier dummy
scoreboard objectives add poi_boolean dummy
scoreboard objectives add poi_max_tier dummy
scoreboard objectives add with_minact_tier dummy
scoreboard objectives add with_boolean dummy
scoreboard objectives add with_max_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add hwait dummy
scoreboard objectives add DB dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add streg dummy
scoreboard objectives add streg1 dummy
scoreboard objectives add stamina dummy
scoreboard objectives add climb dummy
scoreboard objectives add crouch dummy
scoreboard objectives add jump dummy
scoreboard objectives add dealt dummy
scoreboard objectives add sprint dummy
scoreboard objectives add sneaktime dummy
scoreboard objectives add swim dummy
scoreboard objectives add walkowater dummy
scoreboard objectives add walk dummy
scoreboard objectives add walkuwater dummy
scoreboard objectives add insomniaderp dummy
scoreboard objectives add ADD dummy
scoreboard objectives add regud dummy
scoreboard objectives add dsreg dummy
scoreboard objectives add vwl dummy
scoreboard objectives add vwlt dummy
scoreboard objectives add vwl dummy
scoreboard objectives add thirst dummy
scoreboard objectives add treg dummy
scoreboard objectives add drink dummy
scoreboard objectives add thirst dummy
scoreboard objectives add insomnia dummy
scoreboard objectives add DB dummy
scoreboard objectives add DT dummy
scoreboard objectives add death dummy
scoreboard objectives add DB dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add DB dummy
scoreboard objectives add hung_boolean dummy
scoreboard objectives add nau_boolean dummy
scoreboard objectives add weak_boolean dummy
scoreboard objectives add hung_max_tier dummy
scoreboard objectives add weak_max_tier dummy
scoreboard objectives add nau_max_tier dummy
scoreboard objectives add hung_minact_tier dummy
scoreboard objectives add weak_minact_tier dummy
scoreboard objectives add nau_minact_tier dummy
scoreboard objectives add thirst dummy
scoreboard objectives add slimeTick dummy
scoreboard objectives add slimeNegate dummy
scoreboard objectives add slimeTick dummy
scoreboard objectives add slimeNegate dummy
scoreboard objectives add MMfix dummy
scoreboard objectives add MyddraalHit dummy
scoreboard objectives add MyddraalHitb dummy
scoreboard objectives add MMEffectTick dummy
scoreboard objectives add healthb dummy
scoreboard objectives add regulatef dummy
scoreboard objectives add regulateg dummy
scoreboard objectives add outindex dummy
scoreboard objectives add listutils.out dummy
scoreboard objectives add ar_ef_cl_max dummy
scoreboard objectives add all_max dummy
scoreboard objectives add arrow_max dummy
scoreboard objectives add cave_spider_max dummy
scoreboard objectives add cod_max dummy
scoreboard objectives add drag_fire_max dummy
scoreboard objectives add enderman_max dummy
scoreboard objectives add endermite_max dummy
scoreboard objectives add evoker_max dummy
scoreboard objectives add evoker_fangs_max dummy
scoreboard objectives add exper_orb_max dummy
scoreboard objectives add eye_of_end_max dummy
scoreboard objectives add falling_bl_max dummy
scoreboard objectives add hoglin_max dummy
scoreboard objectives add illusioner_max dummy
scoreboard objectives add item_max dummy
scoreboard objectives add fireball_max dummy
scoreboard objectives add llama_spit_max dummy
scoreboard objectives add magma_cube_max dummy
scoreboard objectives add phantom_max dummy
scoreboard objectives add pig_max dummy
scoreboard objectives add piglin_max dummy
scoreboard objectives add piglin_brute_max dummy
scoreboard objectives add pufferfish_max dummy
scoreboard objectives add salmon_max dummy
scoreboard objectives add shulker_max dummy
scoreboard objectives add shu_bul_max dummy
scoreboard objectives add silverfish_max dummy
scoreboard objectives add skeleton_max dummy
scoreboard objectives add slime_max dummy
scoreboard objectives add smal_fire_max dummy
scoreboard objectives add snowball_max dummy
scoreboard objectives add spec_ar_max dummy
scoreboard objectives add spider_max dummy
scoreboard objectives add stray_max dummy
scoreboard objectives add egg_max dummy
scoreboard objectives add ender_pearl_max dummy
scoreboard objectives add exper_bot_max dummy
scoreboard objectives add potion_max dummy
scoreboard objectives add vex_max dummy
scoreboard objectives add vindicator_max dummy
scoreboard objectives add witch_max dummy
scoreboard objectives add with_skul_max dummy
scoreboard objectives add zoglin_max dummy
scoreboard objectives add zombie_max dummy
scoreboard objectives add zom_pig_max dummy
scoreboard objectives add fish_bob_max dummy
scoreboard objectives add sawayig_max dummy
scoreboard objectives add blight_max dummy
scoreboard objectives add machin_shin_max dummy
scoreboard objectives add startworldclock dummy
scoreboard objectives add listindex dummy
scoreboard objectives add loadclock dummy
scoreboard objectives add td dummy
scoreboard objectives add regulate dummy
scoreboard objectives add vregu dummy
scoreboard objectives add regu dummy
scoreboard objectives add regun dummy
scoreboard objectives add atic dummy
scoreboard objectives add blockt2 dummy
scoreboard objectives add lreg dummy
scoreboard objectives add blocktc dummy
scoreboard objectives add moriatica dummy
scoreboard objectives add moriatic dummy
scoreboard objectives add wmoriatic dummy
scoreboard objectives add systic dummy
scoreboard objectives add extrastic dummy
scoreboard objectives add path dummy
scoreboard objectives add blockta dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vpol1 dummy
scoreboard objectives add vpol2 dummy
scoreboard objectives add vpol3 dummy
scoreboard objectives add vpol4 dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vpol1 dummy
scoreboard objectives add vpol2 dummy
scoreboard objectives add vpol3 dummy
scoreboard objectives add vpol4 dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vreg dummy
scoreboard objectives add vwl dummy
scoreboard objectives add vwlt dummy
scoreboard objectives add vwl dummy
scoreboard objectives add vtc dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vpol1 dummy
scoreboard objectives add vpol2 dummy
scoreboard objectives add vpol3 dummy
scoreboard objectives add vpol4 dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vpol1 dummy
scoreboard objectives add vpol2 dummy
scoreboard objectives add vpol3 dummy
scoreboard objectives add vpol4 dummy
scoreboard objectives add vpol dummy
scoreboard objectives add vwl dummy
scoreboard objectives add vwlt dummy
scoreboard objectives add vwl dummy
scoreboard objectives add vtc dummy
scoreboard objectives add aboveground dummy
scoreboard objectives add wt_distancea dummy
scoreboard objectives add wt_distance_inta dummy
scoreboard objectives add wt dummy
scoreboard objectives add storm_inta dummy
scoreboard objectives add storm_intb dummy
scoreboard objectives add storm_clk dummy
scoreboard objectives add wt_distancea dummy
scoreboard objectives add wt_distanceb dummy
scoreboard objectives add wt_distancec dummy
scoreboard objectives add wt dummy
scoreboard objectives add wt_effect_clock dummy
scoreboard objectives add wt_tick dummy
scoreboard objectives add weather dummy
scoreboard objectives add wn_derpa dummy
scoreboard objectives add wn_derpb dummy
scoreboard objectives add windpulse dummy
scoreboard objectives add wind dummy
scoreboard objectives add windspeed dummy
scoreboard objectives add listindex dummy
scoreboard objectives add startworldclock dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add listutils.in dummy
scoreboard objectives add listutils.var dummy
scoreboard objectives add DT dummy
scoreboard objectives add stamina dummy
scoreboard objectives add thirst dummy
scoreboard objectives add stamina dummy
scoreboard objectives add slimeSize dummy
scoreboard objectives add healthb dummy
scoreboard objectives add blockta dummy
scoreboard objectives add moriatic dummy
scoreboard objectives add wmoriatic dummy
scoreboard objectives add systic dummy
scoreboard objectives add extrastic dummy
scoreboard objectives add DT dummy
scoreboard objectives add stamina dummy
scoreboard objectives add thirst dummy
scoreboard objectives add stamina dummy
scoreboard objectives add slimeSize dummy
scoreboard objectives add healthb dummy
scoreboard objectives add blockta dummy
scoreboard objectives add moriatic dummy
scoreboard objectives add wmoriatic dummy
scoreboard objectives add systic dummy
scoreboard objectives add extrastic dummy
scoreboard objectives add  dummy