
function world:ambience/main.0/0
execute if entity @a[scores={tic=10..}] run function world:ambience/main.0/1
execute as @a at @s if entity @s[scores={tic=10..}] run scoreboard players set @s tic 0
execute as @a[scores={biome=0..0}] at @s if entity @a[scores={sky=1..1}] unless entity @e[tag=!notick,type=marker,name=middleocean,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"middleocean"}'}
execute as @a[scores={biome=24..24}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=middleocean,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"middleocean"}'}
execute as @a[scores={biome=46..46}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=middleocean,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"middleocean"}'}
execute as @a[scores={biome=49..49}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=middleocean,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"middleocean"}'}
execute as @a[scores={biome=45..45}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=middleocean,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"middleocean"}'}
execute as @a[scores={biome=48..48}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=middleocean,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"middleocean"}'}
execute as @a[scores={biome=44..44}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=middleocean,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"middleocean"}'}
execute as @a[scores={biome=47..47}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=middleocean,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"middleocean"}'}
execute as @a[scores={biome=16..16}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=oceanwaves,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"oceanwaves"}'}
execute as @a[scores={biome=25..25}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=oceanwaves,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"oceanwaves"}'}
execute as @a[scores={biome=7..7}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=river,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"river"}'}
execute as @a[scores={biome=4..4}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestmain,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestmain"}'}
execute as @a[scores={biome=55..55}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestmain,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestmain"}'}
execute as @a[scores={biome=18..18}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestmain,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestmain"}'}
execute as @a[scores={biome=34..34}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestmain,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestmain"}'}
execute as @a[scores={biome=29..29}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestmain,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestmain"}'}
execute as @a[scores={biome=63..63}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestmain,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestmain"}'}
execute as @a[scores={biome=27..27}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestbirch,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestbirch"}'}
execute as @a[scores={biome=28..28}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestbirch,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestbirch"}'}
execute as @a[scores={biome=61..61}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestbirch,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestbirch"}'}
execute as @a[scores={biome=62..62}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestbirch,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestbirch"}'}
execute as @a[scores={biome=21..21}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=jungle,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"jungle"}'}
execute as @a[scores={biome=22..22}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=jungle,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"jungle"}'}
execute as @a[scores={biome=59..59}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=jungle,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"jungle"}'}
execute as @a[scores={biome=73..73}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=jungle,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"jungle"}'}
execute as @a[scores={biome=74..74}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=jungle,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"jungle"}'}
execute as @a[scores={jungle_edge=23..23}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=jungle,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"jungle"}'}
execute as @a[scores={biome=60..60}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=jungle,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"jungle"}'}
execute as @a[scores={biome=5..5}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=foresttaiga,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"foresttaiga"}'}
execute as @a[scores={biome=19..19}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=foresttaiga,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"foresttaiga"}'}
execute as @a[scores={biome=56..56}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=foresttaiga,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"foresttaiga"}'}
execute as @a[scores={biome=32..32}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=foresttaiga,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"foresttaiga"}'}
execute as @a[scores={biome=33..33}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=foresttaiga,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"foresttaiga"}'}
execute as @a[scores={biome=65..65}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=foresttaiga,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"foresttaiga"}'}
execute as @a[scores={biome=66..66}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=foresttaiga,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"foresttaiga"}'}
execute as @a[scores={biome=30..30}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestsnow,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestsnow"}'}
execute as @a[scores={biome=31..31}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestsnow,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestsnow"}'}
execute as @a[scores={biome=64..64}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=forestsnow,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"forestsnow"}'}
execute as @a[scores={biome=6..6}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=swamp,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"swamp"}'}
execute as @a[scores={biome=57..57}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=swamp,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"swamp"}'}
execute as @a[scores={biome=35..35}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=savanah,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"savanah"}'}
execute as @a[scores={biome=36..36}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=savanah,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"savanah"}'}
execute as @a[scores={biome=68..68}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=savanah,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"savanah"}'}
execute as @a[scores={biome=69..69}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=savanah,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"savanah"}'}
execute as @a[scores={biome=1..1}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=plains,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"plains"}'}
execute as @a[scores={biome=52..52}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=plains,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"plains"}'}
execute as @a[scores={biome=2..2}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=desert,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"desert"}'}
execute as @a[scores={biome=17..17}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=desert,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"desert"}'}
execute as @a[scores={biome=53..53}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=desert,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"desert"}'}
execute as @a[scores={biome=37..37}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=desert,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"desert"}'}
execute as @a[scores={biome=39..39}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=desert,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"desert"}'}
execute as @a[scores={biome=72..72}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=desert,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"desert"}'}
execute as @a[scores={biome=38..38}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=desert,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"desert"}'}
execute as @a[scores={biome=71..71}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=desert,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"desert"}'}
execute as @a[scores={biome=70..70}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=desert,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"desert"}'}
execute as @a[scores={biome=12..12}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=tundra,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"tundra"}'}
execute as @a[scores={biome=58..58}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=tundra,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"tundra"}'}
execute as @a[scores={biome=13..13}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelmountain,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelmountain"}'}
execute as @a[scores={biome=3..3}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=mountain,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"mountain"}'}
execute as @a[scores={biome=20..20}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=mountain,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"mountain"}'}
execute as @a[scores={biome=54..54}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=mountain,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"mountain"}'}
execute as @a[scores={biome=67..67}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=mountain,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"mountain"}'}
execute as @a[scores={biome=18..18}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelwoods,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelwoods"}'}
execute as @a[scores={biome=34..34}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelwoods,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelwoods"}'}
execute as @a[scores={biome=28..28}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelwoods,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelwoods"}'}
execute as @a[scores={biome=62..62}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelwoods,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelwoods"}'}
execute as @a[scores={biome=63..63}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelwoods,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelwoods"}'}
execute as @a[scores={biome=19..19}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelwoods,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelwoods"}'}
execute as @a[scores={biome=56..56}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelwoods,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelwoods"}'}
execute as @a[scores={biome=31..31}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelwoods,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelwoods"}'}
execute as @a[scores={biome=64..64}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelwoods,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelwoods"}'}
execute as @a[scores={biome=33..33}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelwoods,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelwoods"}'}
execute as @a[scores={biome=66..66}] at @s if entity @a[scores={sky=1..1}] unless entity @e[type=marker,name=highlevelwoods,distance=0..10] run summon marker ~ ~ ~ {CustomNameVisible:0b,Tags:["amb","lagcontrol"],NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,CustomName:'{"text":"highlevelwoods"}'}
execute as @a run function world:ambience/main.0/76
execute as @e[tag=amb,type=marker] unless entity @s[scores={ambt=0..1000}] run scoreboard players set @s ambt 1000
execute as @a run scoreboard players operation @s ambt += @e[tag=dmain,type=marker] blockta
execute at @a as @e[tag=amb,distance=0..15] run scoreboard players operation @s ambt += @e[tag=dmain,type=marker] blockta
execute as @a[scores={ambt=5..}] run scoreboard players set @s ambt 0
execute as @e[type=marker,name=desert] run function world:ambience/main.0/81
execute as @e[type=marker,name=forestbirch] run function world:ambience/main.0/82
execute as @e[type=marker,name=forestmain] run function world:ambience/main.0/83
execute as @e[type=marker,name=forestsnow] run function world:ambience/main.0/84
execute as @e[type=marker,name=foresttaiga] run function world:ambience/main.0/85
execute as @e[type=marker,name=highlevelmountain] run function world:ambience/main.0/86
execute as @e[type=marker,name=highlevelwoods] run function world:ambience/main.0/87
execute as @e[type=marker,name=jungle] run function world:ambience/main.0/88
execute as @e[type=marker,name=middleocean] run function world:ambience/main.0/89
execute as @e[type=marker,name=mountain] run function world:ambience/main.0/90
execute as @e[type=marker,name=oceanwaves] run function world:ambience/main.0/91
execute as @e[type=marker,name=plains] run function world:ambience/main.0/92
execute as @e[type=marker,name=river] run function world:ambience/main.0/93
execute as @e[type=marker,name=savanah] run function world:ambience/main.0/94
execute as @e[type=marker,name=swamp] run function world:ambience/main.0/95
execute as @e[type=marker,name=tundra] run function world:ambience/main.0/96
execute at @a as @e[tag=amb,distance=15..] at @s unless entity @a[distance=0..15] unless entity @s[scores={ambt=0..0}] run scoreboard players set @s ambt 0