modLoader="javafml"
loaderVersion="[39,)"
license="Academic Free License v3.0"

[[mods]]
modId="mca"
version="1.8.2"
displayName="Alive | Dynamic Eco Systems & Boss Progression"
credits="Ghostcrafter090, Nightshayd, Sabagegah"
displayURL="http://gsweathermore.ddns.net"
logoFile="logo.png"
authors="Ghostcrafter090"
description='''
Makes many changes to the game, making the game feel more alive without changing the vanilla aspect!
'''

[[dependencies.mca]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"




