






execute at @s as @e[tag=!notick,name=waygate,type=marker,distance=0..100,sort=random,limit=1] at @s positioned ~-1 ~-18 ~2 if entity @e[tag=!notick,type=item_frame,limit=1,sort=nearest,nbt={OnGround:0b,ItemDropChance:1.0f,ItemRotation:3b,Invulnerable:1b,Fixed:0b,Rotation:[90.0f,0.0f],Facing:4b,CustomName:'{"text":"waygate_leaf_loc"}',Item:{id:"minecraft:kelp",tag:{display:{Name:'{"text":"Avendesora Leaf","color":"dark_green","bold":true,"italic":true}',Lore:['{"text":"Use to unlock a waygate."}']}},Count:1b},Invisible:1b,NoGravity:1b}] unless entity @s[scores={gateopen=1..2}] run scoreboard players set @s gateopen 1
execute at @s as @e[tag=!notick,name=waygate,type=marker,distance=0..100,sort=random,limit=1] at @s positioned ~-1 ~-18 ~2 if entity @e[tag=!notick,type=item_frame,limit=1,sort=nearest,nbt={OnGround:0b,ItemDropChance:1.0f,ItemRotation:3b,Invulnerable:1b,Fixed:0b,Rotation:[90.0f,0.0f],Facing:4b,CustomName:'{"text":"waygate_leaf_loc"}',Item:{id:"minecraft:kelp",tag:{display:{Name:'{"text":"Avendesora Leaf","color":"dark_green","bold":true,"italic":true}',Lore:['{"text":"Use to unlock a waygate."}']}},Count:1b},Invisible:1b,NoGravity:1b}] if entity @s[scores={gateopen=2..2}] at @s run fill ~ ~-19 ~1 ~ ~-17 ~-1 air replace gray_stained_glass_pane
execute at @s as @e[tag=!notick,name=waygate,type=marker,distance=0..100,sort=random,limit=1] at @s positioned ~-1 ~-18 ~2 if entity @e[tag=!notick,type=item_frame,limit=1,sort=nearest,nbt={OnGround:0b,ItemDropChance:1.0f,ItemRotation:3b,Invulnerable:1b,Fixed:0b,Rotation:[90.0f,0.0f],Facing:4b,CustomName:'{"text":"waygate_leaf_loc"}',Item:{id:"minecraft:kelp",tag:{display:{Name:'{"text":"Avendesora Leaf","color":"dark_green","bold":true,"italic":true}',Lore:['{"text":"Use to unlock a waygate."}']}},Count:1b},Invisible:1b,NoGravity:1b}] if entity @s[scores={gateopen=2..2}] at @s run fill ~ ~-20 ~1 ~ ~-20 ~-1 cobblestone replace
execute at @s as @e[tag=!notick,name=waygate,type=marker,distance=0..100,sort=random,limit=1] at @s positioned ~-1 ~-18 ~2 if entity @e[tag=!notick,type=item_frame,limit=1,sort=nearest,nbt={OnGround:0b,ItemDropChance:1.0f,ItemRotation:3b,Invulnerable:1b,Fixed:0b,Rotation:[90.0f,0.0f],Facing:4b,CustomName:'{"text":"waygate_leaf_loc"}',Item:{id:"minecraft:kelp",tag:{display:{Name:'{"text":"Avendesora Leaf","color":"dark_green","bold":true,"italic":true}',Lore:['{"text":"Use to unlock a waygate."}']}},Count:1b},Invisible:1b,NoGravity:1b}] if entity @s[scores={gateopen=2..2}] at @s run playsound minecraft:block.portal.trigger master @a ~ ~ ~ 9 2
execute at @s as @e[tag=!notick,name=waygate,type=marker,distance=0..100,sort=random,limit=1] at @s positioned ~-1 ~-18 ~2 if entity @e[tag=!notick,type=item_frame,limit=1,sort=nearest,nbt={OnGround:0b,ItemDropChance:1.0f,ItemRotation:3b,Invulnerable:1b,Fixed:0b,Rotation:[90.0f,0.0f],Facing:4b,CustomName:'{"text":"waygate_leaf_loc"}',Item:{id:"minecraft:kelp",tag:{display:{Name:'{"text":"Avendesora Leaf","color":"dark_green","bold":true,"italic":true}',Lore:['{"text":"Use to unlock a waygate."}']}},Count:1b},Invisible:1b,NoGravity:1b}] if entity @s[scores={gateopen=2..2}] run scoreboard players set @s gateopen 0
execute at @s as @e[tag=!notick,name=waygate,type=marker,distance=0..100,sort=random,limit=1] at @s positioned ~-1 ~-18 ~2 if entity @e[tag=!notick,type=item_frame,limit=1,sort=nearest,nbt={OnGround:0b,ItemDropChance:1.0f,ItemRotation:3b,Invulnerable:1b,Fixed:0b,Rotation:[90.0f,0.0f],Facing:4b,CustomName:'{"text":"waygate_leaf_loc"}',Item:{id:"minecraft:kelp",tag:{display:{Name:'{"text":"Avendesora Leaf","color":"dark_green","bold":true,"italic":true}',Lore:['{"text":"Use to unlock a waygate."}']}},Count:1b},Invisible:1b,NoGravity:1b}] run data merge entity @e[tag=!notick,type=item_frame,limit=1,sort=nearest] {OnGround:0b,ItemDropChance:1.0f,ItemRotation:0b,Invulnerable:1b,Fixed:0b,Rotation:[90.0f,0.0f],Facing:4b,CustomName:'{"text":"waygate_leaf_loc"}',Item:{id:"minecraft:kelp",tag:{display:{Name:'{"text":"Avendesora Leaf","color":"dark_green","bold":true,"italic":true}',Lore:['{"text":"Use to unlock a waygate."}']}},Count:1b},Invisible:1b,NoGravity:1b}