execute as @a[scores={insomnia=25000..,streg1=1..1}] run scoreboard players remove @a stamina 1
execute as @a[scores={insomnia=35000..,streg1=1..1}] run scoreboard players remove @a stamina 1
execute as @a[scores={insomnia=45000..,streg1=1..1}] run scoreboard players remove @a stamina 1
execute as @a[scores={insomnia=55000..,streg1=1..1}] run scoreboard players remove @a stamina 1
execute as @a[scores={insomnia=65000..,streg1=1..1}] run scoreboard players remove @a stamina 1
execute as @a[scores={insomnia=75000..,streg1=1..1}] run scoreboard players remove @a stamina 1
execute as @a[scores={insomnia=85000..,streg1=1..1}] run scoreboard players remove @a stamina 1
execute as @a[scores={insomnia=95000..,streg1=1..1}] run scoreboard players remove @a stamina 1
execute as @a[scores={insomnia=105000..,streg1=1..1}] run scoreboard players remove @a stamina 1
execute as @a[scores={DT=3000..}] run scoreboard players add @s insomnia 1
execute as @a[scores={DT=5000..}] run scoreboard players add @s insomnia 1
execute as @a[scores={DT=7000..}] run scoreboard players add @s insomnia 1